# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 87dcc70a9bfa1e4a97ad4db13d42aefa2e17348cd29356974daaeb2ec42692f951aa541e3721ada7f0e00944de4d6ca2882c9e27e2581750f348d566e5b7324d

test:
  secret_key_base: a52ea904e4fa9bc8a39dbac4f7e3efcc483ae5a11b6fb3b98d703c0e3d7f3a0a2a11a481d4c70153c074293978ae1edc8cd086e9568dfa259af37cc80742adc6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
